// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVHPjW-6PX8Poq8AD4IMizGNyuJBMBbW4',
    appId: '1:338221533504:web:b707e83457d6f59eae12a5',
    messagingSenderId: '338221533504',
    projectId: 'sample-project-1752d',
    authDomain: 'sample-project-1752d.firebaseapp.com',
    storageBucket: 'sample-project-1752d.firebasestorage.app',
    measurementId: 'G-2E2CSDP13J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQW6KtgWYJcaHz7Lv73Mn4Ygzy7E84too',
    appId: '1:338221533504:android:d9b5db46fb8c6893ae12a5',
    messagingSenderId: '338221533504',
    projectId: 'sample-project-1752d',
    storageBucket: 'sample-project-1752d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFTZaic7TBWwAkFYVZMCt-pZamqf0XRpk',
    appId: '1:338221533504:ios:ac2b69092350cbb5ae12a5',
    messagingSenderId: '338221533504',
    projectId: 'sample-project-1752d',
    storageBucket: 'sample-project-1752d.firebasestorage.app',
    iosBundleId: 'com.example.sqllite',
  );
}
